linuxdeepin/dde-dock

plugins/network/item/applet/wirelesslist.cpp, plugins/network/item/applet/wirelesslist.h
https://github.com/linuxdeepin/internal-discussion/issues/1106
Change-Id: I1f02188c5e124ba63176ac5713f7af6afd04e4ca
=> fix: not detect hotspot enabled

plugins/shutdown/CMakeLists.txt, plugins/shutdown/shutdownplugin.cpp
https://tower.im/members/fe996d0d13b642a7867fb2d84080a5a8/?me=1vb
=> disable power options for arm

frame/item/components/appsnapshot.cpp, frame/item/components/appsnapshot.h, frame/item/components/floatingpreview.cpp, frame/item/components/floatingpreview.h, frame/item/components/previewcontainer.cpp
Change-Id: Ia01bc9bc73a2bac53a911effa3095f826d8472be
migration from gerrit
相关 issue：https://github.com/linuxdeepin/internal-discussion/issues/1134
=> fix(preview): hovering preview picture size adjust

frame/util/docksettings.cpp
https://github.com/linuxdeepin/internal-discussion/issues/1271
=> not show trash in plugins context menu under efficient mode

frame/util/abstractpluginscontroller.cpp
https://github.com/linuxdeepin/internal-discussion/issues/1312
=> fix: plugin settings value can not transform to Json value in qt 5.7

frame/item/appitem.cpp, frame/item/appitem.h, frame/item/components/previewcontainer.cpp, frame/item/components/previewcontainer.h
https://github.com/linuxdeepin/internal-discussion/issues/1321
=> fix: preview window can not be raised after clicked preview snapshot

frame/util/utils.h, plugins/network/item/applet/accesspointwidget.cpp, plugins/sound/soundapplet.cpp
https://github.com/linuxdeepin/internal-discussion/issues/1411
=> fix(network): refresh loading icon not align center

plugins/tray/indicatortray.cpp
https://pms.deepin.cn/index.php?m=task&f=view&taskID=5131
=> fix(tray): Adding a keyboard layout for the first time will crash

frame/item/components/previewcontainer.cpp
=> fix(preview): crash when click active item on 2d

frame/item/components/floatingpreview.cpp, frame/item/components/floatingpreview.h, frame/item/components/previewcontainer.cpp, frame/item/components/previewcontainer.h
=> fix(preview): float preview background have wrong offset

plugins/tray/indicatortray.cpp
=> fix(tray): cannot click indicator

plugins/overlay-warning/overlay-warning-plugin.cpp
=> fix(overlay): disable overlay failed

frame/item/components/appsnapshot.cpp, frame/item/components/appsnapshot.h, frame/item/components/previewcontainer.cpp
=> fix(preview): cannot switch preview window

frame/util/dockpopupwindow.cpp
=> fix(plugins): scrolling on the item, popup will hide

plugins/disk-mount/CMakeLists.txt, plugins/overlay-warning/CMakeLists.txt, plugins/power/CMakeLists.txt, plugins/shutdown/CMakeLists.txt, plugins/tray/CMakeLists.txt
Without these links, the build will fail on openSUSE.
=> Link some develop libraries to fix build for some distributions.

frame/item/components/previewcontainer.cpp
I have had pull requested this before but the previous one probably got bugged out. So I'm starting a new one.
@xmuli
=> Fix: Window preview glitch

plugins/network/item/applet/accesspointwidget.cpp, plugins/network/item/applet/wirelesslist.cpp, plugins/network/item/wireditem.cpp, plugins/network/item/wireditem.h, plugins/network/item/wirelessitem.cpp, plugins/network/item/wirelessitem.h, plugins/network/networkitem.cpp, plugins/network/networkitem.h
Note that it needs to be merged together with https://github.com/linuxdeepin/dde-network-utils/pull/15
=> chore: correct multiple typos

plugins/network/item/wirelessitem.cpp, plugins/network/item/wirelessitem.h
wrong network state refresh, the cpu of networkmanager and dde-session-daemon will be high
Log:
=> fix: high cpu

frame/item/appitem.cpp, frame/panel/mainpanelcontrol.cpp, gschema/com.deepin.dde.dock.module.gschema.xml
需要通过命令设置gsettings set com.deepin.dde.dock.module.app removeable false
Log:
Issue: Fixes #338
Change-Id: Idb76a8e28bbd4fae7db5870d07d3432fe4029029
=> feat: 允许锁定任务栏上的图标防止被拖拽删除

frame/item/components/appsnapshot.cpp
The function provided by kwin should be used first, and xcb is second.
Issue: Closed https://github.com/linuxdeepin/developer-center/issues/3137
=> refact: get window preview

plugins/tray/xembedtraywidget.cpp
fix wine systray can't interact
Log: fix wine systray can't interact
=> fix: wine systray can't interact

frame/item/pluginsitem.cpp
fix the 3rd plugins can't show context memu
Log: fix the 3rd plugins can't show context menu
=> fix: the 3rd plugins can't show context menu

debian/changelog
=> fix: keep changelog version format and format the same

frame/util/utils.h, plugins/tray/abstracttraywidget.cpp, plugins/tray/abstracttraywidget.h, plugins/tray/fashiontray/containers/normalcontainer.cpp, plugins/tray/snitraywidget.cpp, plugins/tray/system-trays/systemtrayitem.h, plugins/tray/trayplugin.cpp
trayTyep()函数更正为trayType()函数，Utils::ModuleSettingsPtr函数修正了部分注释
Log: 修复AbstractTrayWidget类和Utils::ModuleSettingsPtr函数的拼写错误
Influence: 对功能无影响
=> fix: 修复一些小的拼写错误

plugins/datetime/datetimewidget.cpp
任务栏短日期根据新增的格式去显示
Log: 任务栏新增短日期格式显示，适配海外用户的需求
Task: https://pms.uniontech.com/task-view-174019.html
Influence: 任务栏日期显示
Change-Id: I48de7591e17c5154eac7676e31dc16b13859509a
=> feat: 任务栏新增短日期格式显示

plugins/sound/soundapplet.cpp
支持华为云等云平台设备无端口的情况
Log:
Task: https://pms.uniontech.com/task-view-165707.html
Influence: 声音
Change-Id: Ibfb470b0bd0a4e55752fa2bd4ed05cffd1c26912
=> feat: 支持无端口设备的显示

plugins/sound/soundapplet.cpp, plugins/sound/sounditem.cpp
需求调整，无声卡设备时，tips 提示错误。
Log: 修复无声卡设备tips显示错误
Bug: https://pms.uniontech.com/bug-view-152967.html
Influence: 声音
Change-Id: I2ba075cdd6fb76f15ca31a0dade86cb7421e1422
=> fix(audio): 修复无声卡设备tips显示错误

lupdate.sh
上传翻译无法识别
Log: 上传翻译无法识别
Influence: 更新翻译
Task: https://pms.uniontech.com/bug-view-152967.html
Change-Id: Id2f7bb5dccddadd8aa910590e5659210d0b3c0b8
=> fix: 上传翻译无法识别问题

plugins/sound/soundapplet.cpp
按产品需求设备标题改为音量
Log: 设备标题改为音量
Bug: https://pms.uniontech.com/bug-view-153205.html
Influence: 声音
Change-Id: Ieeb35804c3552bc0fa86ebef087b8a4f4219ca1f
=> fix(audio): 设备标题改为音量

frame/item/components/appsnapshot.cpp
AppSnapshot截图逻辑使用x的方式在wayland下不适用
Log: 解决wayland下鼠标移动到打开的应用任务栏奔溃的问题
Bug: https://pms.uniontech.com/bug-view-153035.html
Influence: 任务栏功能正常使用
Change-Id: I1a19eba92cf3e2a21d6fe898bb06399101e542ea
=> fix: wayland下鼠标移动到打开的应用任务栏奔溃

plugins/bluetooth/componments/bluetoothadapteritem.cpp
删除QStandardItemModel::takeItem调用后，再进行removeRow调用的代码
当行数无效时，不做移除处理
Log: 修复蓝牙列表不同步的问题
Bug: https://pms.uniontech.com/bug-view-150059.html
Influence: 任务栏-蓝牙列表与控制中心-蓝牙列表保持一致
=> fix: 修复任务栏和控制中心蓝牙列表数据不一致的问题

frame/main.cpp
fix typo: "run-by-stardde" -> "run-by-startdde"
Log: "run-by-stardde" -> "run-by-startdde"
=> fix: "run-by-stardde" -> "run-by-startdde"

cmake/DdeDock/DdeDockConfig.cmake.in
这个 DdeDockConfig.cmake 应该是从 dtkcore 抄了模板，忘了改了
=> fix: include directories should be DDE DOCK DIR

plugins/bluetooth/componments/bluetoothadapteritem.cpp
This reverts commit 09fc6e7b
Change-Id: I9ce274ae00533b937f78ba1b879dba45e952b677
=> Revert "fix: 修复蓝牙连接成功后动画显示问题"

archlinux/PKGBUILD, debian/copyright, rpm/dde-dock.spec
Modify project to pass the REUSE check
Log: Modify project to pass the REUSE check
Task: https://pms.uniontech.com/task-view-185215.html
Change-Id: I491fcd3e179e45fc482ca4e6aa41ff3e91d633b0
=> chore: adapt license and copyright

archlinux/PKGBUILD
dde-network-utils replace to dde-network-core
Log:
=> chore: update makedepends

translations/dde-dock_az.ts, translations/dde-dock_ca.ts, translations/dde-dock_cs.ts, translations/dde-dock_de.ts, translations/dde-dock_el.ts, translations/dde-dock_en_US.ts, translations/dde-dock_es.ts, translations/dde-dock_fi.ts, translations/dde-dock_fr.ts, translations/dde-dock_gl_ES.ts, translations/dde-dock_hr.ts, translations/dde-dock_hu.ts, translations/dde-dock_it.ts, translations/dde-dock_ko.ts, translations/dde-dock_ms.ts, translations/dde-dock_nl.ts, translations/dde-dock_pl.ts, translations/dde-dock_pt.ts, translations/dde-dock_pt_BR.ts, translations/dde-dock_ro.ts, translations/dde-dock_ru.ts, translations/dde-dock_sl.ts, translations/dde-dock_sq.ts, translations/dde-dock_tr.ts, translations/dde-dock_uk.ts
更新翻译
Log: 更新翻译
Task: https://pms.uniontech.com/task-view-202033.html
Influence: 翻译
Change-Id: I94fd93f277994210630e91078ba0968365f79ea2
=> chore: 更新翻译

plugins/dcc-dock-plugin/module_widget.cpp
按UI设计要求调整插件管理标题与说明文字间距
Log: 按UI设计要求调整插件管理标题与说明文字间距
Bug: https://pms.uniontech.com/bug-view-173635.html
Influence: 按UI设计要求调整插件管理标题与说明文字间距
=> fix: 按UI设计要求调整插件管理标题与说明文字间距

plugins/bluetooth/bluetoothplugin.cpp, plugins/onboard/onboarditem.cpp, plugins/onboard/onboarditem.h, plugins/onboard/onboardplugin.cpp, plugins/sound/sounditem.cpp, plugins/sound/sounditem.h, plugins/sound/soundplugin.cpp
调整任务栏插件尺寸
Log: 调整插件尺寸
Influence: 观察任务栏插件是否对齐
Task: https://pms.uniontech.com/task-view-222353.html
=> fix: 调整插件的尺寸

frame/controller/quicksettingcontroller.cpp, frame/controller/quicksettingcontroller.h, frame/window/components/datetimedisplayer.cpp, frame/window/components/datetimedisplayer.h, frame/window/quickpluginwindow.cpp, frame/window/quickpluginwindow.h, frame/window/systempluginwindow.cpp, frame/window/systempluginwindow.h, frame/window/tray/tray_delegate.cpp, frame/window/traymanagerwindow.cpp, frame/window/traymanagerwindow.h, plugins/bluetooth/bluetoothplugin.cpp, plugins/onboard/onboarditem.cpp, plugins/onboard/onboarditem.h, plugins/onboard/onboardplugin.cpp, plugins/pluginmanager/iconmanager.cpp, plugins/pluginmanager/iconmanager.h, plugins/pluginmanager/pluginmanager.cpp, plugins/pluginmanager/pluginmanager.h
鼠标进入的时候，图标显示底色
Log: 优化图标样式
Influence: 图标样式
Task: https://pms.uniontech.com/bug-view-181945.html
=> fix: 优化插件图标样式

frame/window/components/datetimedisplayer.cpp
系统改变字体后，注销后时间日期显示异常；高效模式下，拉动高度时间字体无变化的问题。
Log:
Bug: https://pms.uniontech.com/bug-view-181387.html
Influence: 时间和日期显示。
=> fix: 解决任务栏时间日期文字显示异常的问题。

debian/changelog
更新版本号为:6.0.8
Log:
Task: https://pms.uniontech.com/task-view-227573.html
Influence: 版本号
=> chore: 更新changelog

CMakeLists.txt, archlinux/PKGBUILD, debian/control, frame/CMakeLists.txt, frame/screenspliter/screenspliter_wayland.cpp, plugins/plugin-guide/home_monitor/CMakeLists.txt, plugins/plugin-guide/plugins-developer-guide.md, tests/CMakeLists.txt
fix CMakefile error
fix archlinux build dep
log:
=> fix: fix build

plugins/trash/popupcontrolwidget.cpp
Correct a typo in popupcontrolwidget.cpp
=> chore: correct a typo in popupcontrolwidget.cpp

tests/util/ut_dockpopupwindow.cpp
Fix reference to 'DRegionMonitor' is ambiguous
Log:
=> fix: build failure

plugins/trash/trashwidget.cpp
Correct typos in trashwidget.cpp
=> chore: correct typos in trashwidget.cpp

frame/window/mainwindowbase.cpp
Fixes linuxdeepin/developer-center#3601
=> fix: 修复任务栏圆角跟随窗口圆角变化

frame/item/components/appdrag.cpp, frame/item/pluginsitem.cpp, frame/window/components/desktop_widget.cpp, frame/window/tray/widgets/systempluginitem.cpp, plugins/bluetooth/componments/bluetoothadapteritem.cpp, plugins/bluetooth/componments/bluetoothapplet.cpp, plugins/sound/soundapplet.h
=> chore: remove some deprecated function

frame/window/components/datetimedisplayer.cpp, frame/window/components/datetimedisplayer.h, frame/window/systempluginwindow.cpp, frame/window/systempluginwindow.h, frame/window/traymanagerwindow.cpp, frame/window/traymanagerwindow.h
Add a common function to draw rounded background.
Issue: https://github.com/linuxdeepin/developer-center/issues/3744
=> fix: Missing radius for tray's background

plugins/bluetooth/componments/bluetoothadapteritem.cpp
Closed: https://github.com/linuxdeepin/developer-center/issues/3809
=> fix: bluetooth not refresh button

plugins/pluginmanager/pluginchildpage.cpp, plugins/pluginmanager/pluginchildpage.h
Closed: https://github.com/linuxdeepin/developer-center/issues/3748
=> fix: plugin back button not support hiDPI

plugins/sound/sounddeviceswidget.cpp, plugins/sound/sounditem.cpp, plugins/sound/sounditem.h, plugins/sound/soundplugin.cpp, plugins/sound/soundwidget.cpp
Closed: https://github.com/linuxdeepin/developer-center/issues/3812
Closed: https://github.com/linuxdeepin/developer-center/issues/3865
=> fix: unmute when changed volume

frame/window/tray/widgets/basetraywidget.h, frame/window/tray/widgets/expandiconwidget.cpp, frame/window/tray/widgets/expandiconwidget.h, frame/window/tray/widgets/indicatortrayitem.h, frame/window/tray/widgets/snitrayitemwidget.cpp, frame/window/tray/widgets/snitrayitemwidget.h, frame/window/tray/widgets/systempluginitem.cpp, frame/window/tray/widgets/systempluginitem.h, frame/window/tray/widgets/xembedtrayitemwidget.h
resolve: https://github.com/linuxdeepin/developer-center/issues/3814
=> fix: tray menu is hidden before function call

plugins/pluginmanager/standardquickitem.cpp
=> fix: set limit width to textLabel to correct text elide behavior

frame/window/tray/widgets/snitrayitemwidget.cpp
=> fix: dock crashed while gragging sniItem

frame/window/components/datetimedisplayer.cpp, frame/window/components/datetimedisplayer.h
use local var to store format, update those when got changed signals
log:
=> fix: fix timedate alway request timedate format

frame/item/components/appsnapshot.cpp, frame/item/components/floatingpreview.cpp, frame/item/components/previewcontainer.cpp
Log: 由于相关接口被移除，暂时无法正确设置 m_closeAble 属性，暂改为默认 true
Task: https://github.com/linuxdeepin/developer-center/issues/3608
确实可能有无法关闭的窗口，暂时先不删除
=> fix: dont hide all close button

CMakeLists.txt, debian/changelog
=> chore: bump version 6.0.11

plugins/pluginmanager/linequickitem.cpp, plugins/pluginmanager/linequickitem.h, plugins/pluginmanager/quicksettingitem.cpp
=> fix: tray background color not set alpha

plugins/plugin-guide/plugins-developer-guide.md
line:579 这一段话可以放在代码块外面
line:744 拼写错误，应该是label而不是lable
line:780 这一段注释可以作为正文放在代码块外面
共3处修改。
Log: 修改了 dde-dock/plugins/plugin-guide/plugins-developer-guide.md 的几处问题
=> docs: 修改了 dde-dock/plugins/plugin-guide/plugins-developer-guide.md 的几处问题

debian/changelog
=> chore: bump version 6.0.12

frame/window/traymanagerwindow.cpp
bad indentation of else and unused count value
Log: find some bad code and fix
=> chore: bad code fix

plugins/bluetooth/bluetoothmainwidget.cpp, plugins/pluginmanager/largerquickitem.cpp, plugins/pluginmanager/standardquickitem.cpp
Log: make only Left mouse click will trigger the command of plugin
resolve: https://github.com/linuxdeepin/developer-center/issues/3753
=> fix: not left mouse click will also trigger the command of plugin

frame/util/multiscreenworker.cpp
dock request to hide, set old position to appitem. so need to update appitem position when show from hide state
resolve: https://github.com/linuxdeepin/developer-center/issues/4156
log: update appitem position
=> fix: update appitem position when showing from hide

CMakeLists.txt, debian/changelog
=> chore: bump version 6.0.13

frame/window/tray/widgets/snitrayitemwidget.cpp
Choose the pixmap that fits best in size.
Fixes linuxdeepin/developer-center#4185
=> fix: fcitx5 keyboard tray icon blur

frame/CMakeLists.txt
add missing library links
Log: Need link these libraries to make sure the build will be successful
=> fix: add missing library links

frame/window/mainwindowbase.cpp, frame/window/mainwindowbase.h
=> fix: window radius is not set

CMakeLists.txt, debian/changelog
=> chore: bump version 6.0.14

frame/util/dockpopupwindow.cpp
set the minimum value of x of popupwindow to the current screen and the maximum value to the maximum x of the current screen
log:
=> fix: popupwindow is out of bounds at the edge of the screen

.gitignore, CMakeLists.txt, frame/main.cpp
Log: use version from cmake
发现dde-dock --version 返回是2.0
=> chore: use version from cmake

CMakeLists.txt, debian/changelog
=> chore: bump version 6.0.16

CMakeLists.txt, plugins/pluginmanager/quicksettingcontainer.h, plugins/sound/sounddeviceswidget.h
fix some build error aft dtk update
=> fix: build error

debian/control
=> chore: update dependencies

widgets/tipswidget.cpp
Closed: https://github.com/linuxdeepin/developer-center/issues/4350
=> fix: tips font size not follow system

frame/main.cpp, frame/taskmanager/taskmanager.cpp, frame/util/singleton.h, frame/window/mainwindowbase.cpp
Resolve: https://github.com/linuxdeepin/developer-center/issues/5019
=> fix: dock entry not update after docker display mode changed

CMakeLists.txt, debian/changelog
=> chore: bump version 6.0.18

frame/dbus/dockdaemonadaptors.cpp
add positionModeChanged signal to dbus
log: as title
=> fix: no positionModeChanged signal

frame/taskmanager/dbushandler.cpp, frame/taskmanager/dbushandler.h, frame/taskmanager/taskmanager.cpp, frame/taskmanager/taskmanager.h, frame/util/multiscreenworker.cpp
add lost launcherFront dbus signal
log: as title
=> fix: not show with launcher when hide

frame/dbus/dockdaemonadaptors.cpp
=> fix: add hideModeChanged signal

plugins/sound/sounddeviceswidget.cpp, plugins/sound/sounddeviceswidget.h, widgets/slidercontainer.cpp, widgets/slidercontainer.h
log: add a timer to set once in 50 ms
=> fix: adjust the slider to set the sound multiple times

frame/taskmanager/taskmanager.cpp, frame/taskmanager/taskmanager.h, frame/window/tray/widgets/expandiconwidget.cpp
log: prevent dock hide as dde-launcher show shen trayGridWIdget show
=> fix: dock autohide even trayGridWidget show

frame/dbus/dockdaemonadaptors.cpp
=> fix: no displayModeChanged signal

CMakeLists.txt, debian/changelog
=> chore: bump version 6.0.20

frame/dbus/dockdaemonadaptors.cpp
=> fix: add lost windowSizeChanged Signal

frame/main.cpp, frame/taskmanager/x11manager.cpp, plugins/display/brightnessmodel.cpp, plugins/display/brightnessmodel.h, plugins/display/brightnesswidget.cpp, plugins/display/brightnesswidget.h
=> fix: brightness update, update main view slider

frame/controller/recentapphelper.cpp, frame/controller/recentapphelper.h, frame/taskmanager/appinfo.cpp, frame/taskmanager/common.h, frame/taskmanager/dbushandler.cpp, frame/taskmanager/dbushandler.h, frame/taskmanager/desktopinfo.cpp, frame/taskmanager/desktopinfo.h, frame/taskmanager/entry.cpp, frame/taskmanager/taskmanager.cpp, translations/dde-dock.ts, translations/dde-dock_zh_CN.ts
=> feat: use new am dbus interface

frame/window/components/datetimedisplayer.cpp, frame/window/components/datetimedisplayer.h, frame/window/traymanagerwindow.cpp
make font size adjusted by height or width not follow system font size
log: as title
=> fix: datetime font size error

debian/changelog
=> chore: bump version 6.0.21

frame/window/docktraywindow.cpp
the m_mainBoxLayout last call addStretch, so tary show insert into second last
log: make tray insert into second last
=> fix: a space on tray without trash show

frame/controller/toolapphelper.cpp, frame/window/components/datetimedisplayer.cpp
fix datetime size error
fix toolAreaWidget size error
=> fix: dock size error

CMakeLists.txt, debian/changelog
=> chore: release version 6.0.22

frame/window/tray/tray_gridview.cpp
editor auto close when drag finished, but on one reopen
log: reopen editor when drag finished
=> fix: tray disappear when drag finished

frame/window/tray/tray_model.cpp, frame/window/tray/tray_model.h
tray show on dock signal name is quickTrayNameChanged
log: connect right signal name
=> fix: double tray show afeter drag into expandTray and drag back

frame/window/components/datetimedisplayer.cpp, frame/window/components/datetimedisplayer.h
Adapt time format feature from dcc
Issue: https://github.com/linuxdeepin/developer-center/issues/5902
=> chore: Adapt time format feature

debian/changelog
update version to 6.0.23
Log: update version to 6.0.23
=> chore: update version to 6.0.23

frame/util/dockpopupwindow.cpp
=> chore: when debug open this log

frame/taskmanager/taskmanager.cpp
=> chore: xid is drop in debug, cause coredump

frame/dbus/dbusdockadaptors.cpp, plugins/trash/CMakeLists.txt, plugins/trash/popupcontrolwidget.cpp
This reverts commit 58547b091d4a5baea4352d88ff1ad21d8116a980.
=> Revert "fix: dcc dock plugin icon pixelated"

debian/changelog
=> chore: publish new tag 6.0.24

debian/changelog, translations/dde-dock_zh_CN.ts
update translations
release 6.0.26
=> update translations && bump version to 6.0.26 

frame/controller/dockitemmanager.cpp, frame/controller/quicksettingcontroller.cpp, frame/util/abstractpluginscontroller.cpp, frame/util/pluginloader.cpp, frame/util/pluginloader.h, plugins/pluginmanager/dockplugincontroller.cpp
+ Use QMetaObject::invokeMethod
+ Correct typo found
=> Optimize some calls and correct typos

configs/com.deepin.dde.dock.json
Issue: https://github.com/linuxdeepin/developer-center/issues/6486
=> chore: uosai default show on dock (#6486)

plugins/notification/notification.cpp, plugins/notification/notification.h, plugins/notification/notificationplugin.cpp, plugins/notification/notificationplugin.h, translations/dde-dock.ts, translations/dde-dock_en_US.ts, translations/dde-dock_zh_CN.ts
Add notification settings action. Notification tips label will display notification count.
Log: fix notification tips label and context menu
=> fix: notification tips label and context menu

frame/taskmanager/windowidentify.cpp
org.ayatana.bamf dbus will get into stucked , so only call it when it's ready
log: only call org.ayatana.bamf when it's ready
issue: https://github.com/linuxdeepin/developer-center/issues/6657
=> fix: dock get stucked when launching

debian/control, frame/window/components/datetimedisplayer.cpp, frame/window/components/datetimedisplayer.h
timedate tips should bind region format
Log:
=> fix: timedate tips show error

frame/dbus/dockdaemonadaptors.cpp, frame/dbus/dockdaemonadaptors.h, frame/taskmanager/taskmanager.cpp, frame/taskmanager/taskmanager.h
Add dbus property WindowMargin for other application to calculate the real exclusiveArea.
Log: add dbus property window margin
=> feat: add dbus property window margin

frame/taskmanager/dbushandler.cpp
try to call bamf
log: as title
=> fix: no one call bamf

frame/window/components/datetimedisplayer.cpp
=> fix: when dconfig no value, use system format

plugins/display/displaysettingwidget.cpp, plugins/display/displaysettingwidget.h, translations/dde-dock.ts, translations/dde-dock_zh_CN.ts
=> chore: bring back display setting button

CMakeLists.txt, debian/changelog
=> chore: bump version to 6.0.30

debian/changelog
=> chore: release 6.0.31

frame/window/tray/tray_model.cpp
rowCountChanged signal not send
log: send rowCountChanged signal
issue: https://github.com/linuxdeepin/developer-center/issues/7080
=> fix: dock not remove plugin when fcitx exit

frame/main.cpp
reset dock dapplication palettetype to 0
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7090
=> fix: dock theme not follow system

CMakeLists.txt, debian/changelog
bump version 6.0.33
log: as title
=> chore: bump version 6.0.33

frame/util/multiscreenworker.cpp
Issue: https://github.com/linuxdeepin/developer-center/issues/7143 Log:
=> fix: dock animation broken

frame/util/multiscreenworker.cpp, frame/util/multiscreenworker.h
Issue: https://github.com/linuxdeepin/developer-center/issues/7129 Log:
=> fix: dock will not auto hide after set size

frame/taskmanager/taskmanager.cpp, frame/taskmanager/taskmanager.h, frame/util/multiscreenworker.cpp
make dock not hide when click plugin and popup show even in keep hide mode
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7132
=> fix: dock plugin unable to click when in keep hide

plugins/bluetooth/bluetoothmainwidget.cpp
Issues: linuxdeepin/developer-center#7222
=> fix: popup panel cannot be opened when clicking the labels

CMakeLists.txt, debian/changelog
=> chore: bump version 6.0.36

CMakeLists.txt, debian/changelog
release 6.0.37
Log: bump version to 6.0.37
=> chore: bump version to 6.0.37

plugins/shutdown/CMakeLists.txt
Log: fix build error on openSUSE
=> fix: Need link Xcursor for shutdown plugin
