frame/item/components/appsnapshot.cpp
frame/item/components/appsnapshot.h
frame/item/components/previewcontainer.cpp
frame/item/components/previewcontainer.h

防止鼠标划过就进预览了，但是点击的时候对象还未赋值，导致空指针崩溃。

fix: quick click on the preview window will crash

---

plugins/power/dbus/dbuspower.cpp
plugins/power/powerplugin.cpp
plugins/power/powerplugin.h
plugins/power/powerstatuswidget.cpp

Add remaining time to battery indicator widget tip, solving [issue#46](https://github.com/linuxdeepin/dde-control-center/issues/46) and [issue#96](https://github.com/linuxdeepin/dde-dock/issues/96)
Fix battery icon not updating when charging (tested on my matebook d) fixing https://github.com/linuxdeepin/dde-desktop/issues/39 
More details in commit messages

Battery time left and icon fix

---

frame/util/abstractpluginscontroller.cpp
frame/util/pluginloader.cpp
frame/window/mainwindow.cpp
plugins/datetime/datetimeplugin.cpp
plugins/overlay-warning/overlay-warning-plugin.h
plugins/tray/trayplugin.cpp

删除影响的延时器和调整部分构造函数，使其可以快速的完成插件的加载，插件的初始化函数将在其他线程被执行。

调整dock初始化插件的时间

---

frame/item/appitem.cpp

mark m_drag to nullptr when the app drag widget destroyed
当drag对应的控件销毁时，应当将 m_drag 置为空

fix: crash at AppDragWidget

---

frame/window/mainwindow.cpp

Fix dede-dock set to right angle after every logout or reboot
Log:

fix: Fix dode-dock incorrectly set to right angle

---

.packit.yaml
rpm/dde-dock.spec

This commit contains the specfile for building the official package for Fedora
with a Packit setup.
Ultimately, a unified specfile is targeted for Fedora and any other rpm-based
distributions, e.g. openEuler.
And Packit(https://packit.dev/) is a tool for maintaining specfile within
upstream source. It requires a simple config file(.packit.yaml).
Log: Initial packit setup
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

feat: Initial packit setup

---

rpm/dde-dock.spec

This program requires gtest to build.
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

fix: rpm BuildRequires gtest-devel

---

rpm/dde-dock.spec

Fedora no longer installs make in the default build environment.
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

fix: rpm BuildRequires make

---

frame/window/mainpanelcontrol.cpp

第三方插件设置了sizePolicy，但是仍然被遮挡，这是因为dock中未对插件的sizePolicy作出判断，当前已修改
Log: 修复第三方插件sizePolicy无效问题
Influence: 第三方插件宽高

fix: 修复插件sizePolicy无效的问题

---

frame/item/components/appsnapshot.cpp

The function provided by kwin should be used first, and xcb is second.
Issue: Closed https://github.com/linuxdeepin/developer-center/issues/3137
Log: 重构获取窗口预览的方式

refactor: get window preview

---

archlinux/PKGBUILD

add deepin-control-center-git to build dep
Log:

fix: missing deepin-control-center-git

---

frame/display/displaymanager.cpp
frame/display/displaymanager.h

之前wayland下主屏数据的错误已经在dwayland中进行了修复。这部分需要改回来
Log: 任务栏主屏改变信号由qt接口获取，保持数据源统一
Influence: 任务栏跟随主屏显示的功能
Bug: https://pms.uniontech.com/bug-view-146451.html
Change-Id: I0b9217a476ef814ca4d793e16e2c31a1b54d11cb

chore: 任务栏主屏改变信号由qt接口获取，保持数据源统一

---

frame/util/multiscreenworker.cpp

当设置为一直隐藏模式时，按照当前隐藏的状态去设置任务栏区域信息，否则，按照当前显示模式去设置
防止在智能隐藏模式下任务栏的位置更新了，没有去更新后端任务栏的位置，导致任务栏显示状态异常
Log: 解决任务栏自动隐藏模式下调整位置后显示异常的问题
Bug: https://pms.uniontech.com/bug-view-149555.html
Influence: 任务栏正常显示
Change-Id: I58334a4f0d99372e8f170f4d355464ce001f3af6

fix: 任务栏自动隐藏模式下调整位置后显示异常

---

frame/util/dockpopupwindow.cpp

原因：任务栏弹窗的层级为override，锁屏的层级为onScreenDisplay，无法盖住任务栏弹窗。
修改方案：原则上不应该有应用的层级为override，将弹窗的层级降低为onScreenDisplay，经测试不会引入问题。
Log: 修复音量窗口显示在锁屏上方的问题
Bug: https://pms.uniontech.com/bug-view-123485.html
Influence: 任务栏弹窗后锁屏的场景
Change-Id: I0dcab55e0370af42f0011f41b5f5f07122f85ddc

fix: 音量窗口显示在锁屏上方

---

plugins/bluetooth/componments/bluetoothapplet.cpp

任务栏蓝牙插件添加滚动滑动条，并支持触控屏滑动
Log: 任务栏蓝牙插件添加滚动滑动条，并支持触控屏滑动
Influence: 任务栏蓝牙插件
Bug: https://pms.uniontech.com/bug-view-151735.html
Change-Id: I05d27726da68dfd634d58df38ab42ce81cbb3bdc

fix: 任务栏蓝牙插件添加滚动滑动条，并支持触控屏滑动

---

plugins/sound/soundapplet.cpp

对带HDMI外接音频端口的设备调整分辨率会影响端口状态，
dock会激活设备，这与产品设计不符合，禁用端口可以是激活的端口。
Log: 修复调整分辨率导致禁用的声音面板可以设置问题
Bug: https://pms.uniontech.com/bug-view-153899.html
Influence: 声音任务栏显示
Change-Id: Ic2602a1c99ba96cd91d52fb7db679b24bfc45622

fix(audio): 修复调整分辨率导致禁用的声音面板可以设置问题

---

plugins/sound/soundapplet.cpp

任务栏音量调节面板标题部分只作为显示用，无输出端口时不需要设置功能禁用。以免置灰时字体显示不显示
Log: 修复无输出端口时音量面板的标题显示不明显问题
Bug: https://pms.uniontech.com/bug-view-153875.html
Influence: 音量面板的标题清晰显示

fix:  任务栏音量调节面板标题部分不需要禁用

---

frame/util/dockpopupwindow.cpp

设置预览界面层级为dock,和任务栏同级，避免预览时将预览界面自动隐藏，造成刚开始预览就退出预览的问题
Log: 修复鼠标悬停任务栏预览窗口，预览界面闪烁一次就消失的问题
Bug: https://pms.uniontech.com/bug-view-154859.html
Influence: 正常预览应用

fix: 设置预览界面层级和任务栏同级

---

plugins/airplane-mode/airplanemodeplugin.cpp
plugins/airplane-mode/airplanemodeplugin.h

需要关联设备信号,刷新飞行模式
Log: 飞行模式热插拔显示和隐藏
Influence: 飞行模式
Task: https://pms.uniontech.com/bug-view-155145.html

fix: 热插拔无线网卡后飞行模式没有显示

---

CMakeLists.txt
cmake/DdeDock/DdeDockConfig.cmake
cmake/DdeDock/DdeDockConfig.cmake.in
dde-dock.pc.in
frame/CMakeLists.txt
plugins/keyboard-layout/CMakeLists.txt

1 cmake 在 install 时优先使用 GNUInstallDirs
2 修复 pkgconfig 路径
3. 适配 DdeDockConfig.cmake 路径
4. set 前 检查版本号是否已设置
相关：https://github.com/linuxdeepin/developer-center/issues/3167

chore: use GNUInstallDirs in CmakeLists

---

CMakeLists.txt

dpkg-architecture 是 debian 系系统才有的，并不通用
我没有 sw_64 的机器测试，不过 CMAKE_SYSTEM_PROCESSOR 的做法在 dde 其他项目已经使用
比如 https://github.com/linuxdeepin/deepin-editor/blob/master/CMakeLists.txt#L17 ，应该没问题

chore: use CMAKE_SYSTEM_PROCESSOR to check sw_64

---

gschema/com.deepin.dde.dock.module.gschema.xml

修改仅主屏显示的默认值
Log: 修改仅主屏显示的默认值为true
Bug: https://pms.uniontech.com/bug-view-151733.html
Influence: 任务栏主屏显示

fix: 将任务栏插件仅主屏显示设置的默认值设置为true

---

frame/util/multiscreenworker.cpp

没有显示器的时候,qt会虚拟一个空的屏幕,这个时候任务栏没必要处理虚拟屏幕下size
Log: 修复pgv双屏下仅单屏显示,同时拔掉两个显示任务栏崩溃的问题
Influence: 任务栏
Bug: https://pms.uniontech.com/bug-view-159531.html
Change-Id: I011ce6f78a0260507e3aa0c5be12646baa879cd0

fix: 修复pgv双屏下仅单屏显示,同时拔掉两个显示任务栏崩溃的问题

---

frame/util/multiscreenworker.cpp

响应了太多屏幕信息变化，将大量重复调用去掉
monitorUpdateTimer 本来就可以更新位置
Bug: https://pms.uniontech.com/bug-view-158709.html
Log: 修复wayland dock位置异常问题
Influence: wayland dock position incorrect
Change-Id: Ia686089736d6077b47d44c2eaecfbc4240400501

fix: 多次切换显示模式后dock位置异常的问题

---

plugins/bluetooth/componments/bluetoothadapteritem.cpp

连接需要PIN码的蓝牙设备，连接中的动画控件还停留在旧的位置，连接成功，该状态立即隐藏
Log:
Influence: 任务栏-蓝牙插件-连接需要PIN码的蓝牙设备连接成功，蓝牙列表状态显示正常
Bug: https://pms.uniontech.com/bug-view-159331.html

fix: 修复蓝牙连接成功后动画显示问题

---

frame/item/components/previewcontainer.cpp

修改背景： 任务栏该模块代码很久未做改动，本地发现该问题仅在wayland下出现，问题已与窗管对接沟通过，根据窗管建议，上层进 规避，避免因底层强行修改引入新的问题
修复方式： 在wanland下，预览时点击之前取消预览，然后再激活窗口，进行规避
Log: 修复点击预览窗口，键盘失去焦点的问题
Influence: 任务栏-点击预览窗口，任务栏操作正常
Bug: https://pms.uniontech.com/bug-view-159303.html

fix: 修复点击预览窗口，屏幕键盘失去焦点问题

---

plugins/sound/sounditem.cpp

分级标准不一致,统一修改为0.3和0.6
Log: 修复osd和插件音量显示不一致的情况
Bug: https://pms.uniontech.com/bug-view-159535.html
Influence: 音量显示
Change-Id: Ib8245c62d8c8fca30f041602294a3764c81ced6c

fix: 修复osd和插件音量显示不一致的情况

---

frame/window/mainwindow.cpp
frame/window/mainwindow.h

在部分时机，任务栏在设置始终隐藏后仍然会显示，例如，来回切换主屏
这是因为之前wayland下的修改，会强制显示任务栏，避免任务栏界面被qwayland库的接口隐藏
Log: 修复始终隐藏任务栏的配置项失效的问题
Influence: 任务栏的始终隐藏配置
Change-Id: Ib3f8070445a511c523f116b1668969bfd20f4690

fix: 修复始终隐藏任务栏的配置项失效的问题

---

frame/util/multiscreenworker.cpp
frame/util/multiscreenworker.h

wayland环境下计算时尚模式的strut时没有加上 margin，导致应用最大化的时候与任务栏区域有重叠
Log: 修复时尚模式应用最大化与任务栏有重叠区域的问题
Bug: https://pms.uniontech.com/bug-view-157187.html
Influence: 任务栏时尚模式
Change-Id: I23dfdb44ce96358d96fc289ca19bcf49c3d90994

fix: 时尚模式strut设置错误

---

plugins/bluetooth/componments/bluetoothadapteritem.cpp

根据系统主题的类型去调整蓝牙名称的显示
Log: 修复深色系统主题下任务栏蓝牙列表的蓝牙名称显示异常的问题
Bug: https://pms.uniontech.com/bug-view-138011.html
Influence: 任务栏蓝牙名称显示
Change-Id: I697b7304157652085dc0e8fe0ab6e407575128c8

fix: 深色系统主题下任务栏蓝牙列表的蓝牙名称显示异常

---

plugins/bluetooth/componments/bluetoothadapteritem.cpp

移除QStandardItem后，与其绑定的DViewItemAction对象的geometry没有变化导致还显示在原位置 修复方案是：手动更新action的位置，后期DTK组会针对该问题进行优化。
Log:
Influence: 任务栏-蓝牙列表-连接后，列表正常显示
Bug: https://pms.uniontech.com/bug-view-159331.html

fix: 修复蓝牙列表连接后显示异常问题

---

plugins/tray/snitraywidget.cpp

原因：创建sniTrayWidget的时候使用异步的方式获取sni的id，此时一定是空的，进而无法通过ID获取到正确的位置 解决方案：使用同步的方式获取ID
PS：dbus interface的可用性已经在线程中得到了验证，此时使用同步的方式获取，理论上不会出现阻塞的问题。
Log:
Bug: https://pms.uniontech.com/bug-view-162899.html
Influence: 托盘插件位置
Change-Id: I1283bfa560879cc9202c08e72cc20953c2964e5d

fix: 无法记住输入法的位置

---

cmake/DdeDock/DdeDockConfig.cmake
frame/item/appitem.cpp
frame/item/components/appdragwidget.cpp
frame/item/dockitem.cpp
frame/item/dockitem.h
frame/item/pluginsitem.cpp
frame/item/pluginsitem.h
widgets/tipswidget.cpp

只有预览应用时界面圆角为18其他tips圆角为6, 并且tips高度根据内容计算高度再加4像素
Log: 修复任务栏应用tips框样式问题
Bug: https://pms.uniontech.com/bug-view-166289.html
Influence: 任务栏tips正常显示

fix: 只有预览应用时界面圆角为18其他tips圆角为6

---

configs/org.deepin.dde.dock.json
frame/window/components/desktop_widget.cpp
frame/window/components/desktop_widget.h
frame/window/mainpanelcontrol.cpp
frame/window/mainpanelcontrol.h
frame/window/mainwindow.cpp

不影响默认行为，默认该配置为 0 即立刻显示或恢复
如果需要可以进行 dconfig 配置
Log: 添加配置显示桌面的悬浮时间
Change-Id: I0b394bf02717b6ba1abe1e5c86fab82d314f39fc

feat: 添加配置 hover 显示桌面的时间

---

cmake/DdeDock/DdeDockConfig.cmake
frame/controller/dockpluginscontroller.cpp
plugins/tray/system-trays/systemtrayscontroller.cpp

修复在显示其他插件的Tips时无法弹出网络列表输入密码问题
Log: 修复在显示其他插件的Tips时无法弹出网络列表输入密码问题
Task: https://pms.uniontech.com/task-view-212979.html
Influence: 在显示其他插件的TIps或控制面板时，网络列表正常弹出

fix: 修复在显示其他插件的Tips时无法弹出网络列表输入密码问题

---

frame/item/components/floatingpreview.cpp

按UI设计要求修改预览界面关闭按钮样式
Log: 修复应用预览图关闭按钮样式错误问题
Bug: https://pms.uniontech.com/bug-view-167311.html
Influence: 按设计要求样式显示预览图关闭按钮

fix: 修改预览界面关闭按钮样式

---

plugins/tray/indicatortraywidget.cpp
plugins/tray/indicatortraywidget.h

keyboard的显示方式和其他托盘颜色格格不入，修改成统一风格；
浅色模式且任务栏高度最小时显示黑色，其他情况显示白色；
Log: keyboard交互调整
Change-Id: I6c56d9cb08872caac7b3614bb0117e5a5427a17d

feat: keyboard交互调整

---

plugins/bluetooth/componments/bluetoothapplet.cpp

当开启飞行模式后，只禁用(置灰）蓝牙适配器列表一栏，而不是置灰整个蓝牙面板
Log: 修复点击任务栏蓝牙设置不能正常唤起控制中心的问题
Bug: https://pms.uniontech.com/bug-view-171999.html
Influence: 任务栏蓝牙面板正常显示/正常使用
Change-Id: Ib1549cf28736ce2dc780b9b0427a7a472dbd4ab8

fix: 点击任务栏蓝牙设置不能正常唤起控制中心

---

plugins/bluetooth/componments/bluetoothadapteritem.cpp

刷新图标资源应为蓝牙资源内
Log: 修改蓝牙刷新图标为空问题
Bug: https://pms.uniontech.com/bug-view-172931.html
Influence: 任务栏-蓝牙列表-蓝牙刷新图标

fix: 修改蓝牙刷新图标为空问题

---

plugins/onboard/onboardplugin.cpp
plugins/trash/trashplugin.cpp

修改屏幕键盘和回收站默认在任务栏不显示
Log: 修改屏幕键盘和回收站默认在任务栏不显示
Task: https://pms.uniontech.com/task-view-212929.html
Influence: 屏幕键盘和回收站默认在任务栏不显示

feat: 修改屏幕键盘和回收站默认在任务栏不显示

---

frame/main.cpp
frame/util/imageutil.cpp
plugins/multitasking/CMakeLists.txt
plugins/multitasking/multitaskingwidget.cpp
plugins/onboard/onboarditem.cpp
plugins/overlay-warning/overlaywarningwidget.cpp
plugins/power/powerstatuswidget.cpp
plugins/show-desktop/CMakeLists.txt
plugins/show-desktop/showdesktopwidget.cpp
plugins/shutdown/CMakeLists.txt
plugins/shutdown/shutdownwidget.cpp
plugins/trash/trashwidget.cpp

高分屏支持设置错误
Log: 修复任务栏图标模糊问题
Bug: https://pms.uniontech.com/bug-view-174459.html
Influence: 控制中心-开启个人热点

fix: 修复任务栏图标模糊问题

---

frame/main.cpp
frame/util/imageutil.cpp
plugins/multitasking/CMakeLists.txt
plugins/multitasking/multitaskingwidget.cpp
plugins/onboard/onboarditem.cpp
plugins/overlay-warning/overlaywarningwidget.cpp
plugins/power/powerstatuswidget.cpp
plugins/show-desktop/CMakeLists.txt
plugins/show-desktop/showdesktopwidget.cpp
plugins/shutdown/CMakeLists.txt
plugins/shutdown/shutdownwidget.cpp
plugins/trash/trashwidget.cpp

高分屏支持设置错误
Log: 修复任务栏图标模糊问题
Bug: https://pms.uniontech.com/bug-view-174459.html Influence: 缩放后任务栏-各插件图标，右键菜单图标
(cherry picked from commit 3e26d6ca35196130657e13e7361be08542ba8195)

fix: 修复任务栏图标模糊问题 (#729)

---

configs/org.deepin.dde.dock.json
frame/util/multiscreenworker.cpp
frame/util/multiscreenworker.h

任务栏智能隐藏或一直隐藏时，鼠标移动到屏幕边缘过一段时间再唤起任务栏
DConfig配置：delayIntervalOnHide，默认值0，单位毫秒
Log: 隐藏显示动画调整
Change-Id: I3a93a868e790566b6548f83ff740f5913db9bcc8

feat: 隐藏显示动画调整

---

plugins/bluetooth/componments/bluetoothadapteritem.cpp
plugins/bluetooth/componments/bluetoothadapteritem.h
plugins/bluetooth/componments/bluetoothapplet.cpp
plugins/bluetooth/componments/bluetoothapplet.h

1、删除使用错误的调色板，直接使用系统默认调色板。
2、蓝牙设备不可用时使能开关按钮，不禁用整个界面，避免界面文字内容显示不清晰
Log: 控制中心-个性化内设置为深色，从任务栏打开蓝牙面板后，蓝牙设置字体未变成浅色
Bug: https://pms.uniontech.com/bug-view-176333.html
Influence: 蓝牙设置字体跟随系统主题变化

fix: 蓝牙设备不可用时使能开关按钮

---

plugins/airplane-mode/airplanemodeitem.cpp

修复在1.5倍缩放时飞行模式图标显示过小问题
Log: 修复在1.5倍缩放时飞行模式图标显示过小问题
Bug: https://pms.uniontech.com/bug-view-177345.html
Bug: https://pms.uniontech.com/bug-view-176473.html
Influence: 设置缩放后飞行模式图标正常显示

fix: 修复在1.5倍缩放时飞行模式图标显示过小问题

---

frame/controller/dockitemmanager.cpp
frame/controller/dockitemmanager.h
frame/item/appitem.cpp
frame/item/appitem.h
frame/window/mainpanelcontrol.cpp
frame/window/mainpanelcontrol.h
frame/window/mainwindow.cpp

在应用去驻留在任务栏或者驻留的应用在任务栏坐标有变化时，通过wayland协议去设置最小化窗口的位置
Log: 修复wayland下最小化魔灯效果显示异常的问题
Bug: https://pms.uniontech.com/bug-view-111637.html
Influence: wayland下应用窗口最小化显示效果
Change-Id: I56aef594ff0406f5d0bca42f0a4265ffac6398f4

fix: wayland下最小化魔灯效果显示异常

---

frame/util/dockpopupwindow.h
plugins/tray/system-trays/systemtrayscontroller.cpp
tests/util/ut_dockpopupwindow.cpp

指针异常
Log: 修复插入U盘后导致的崩溃问题
Influence: 反复插拔u盘任务栏崩溃
Bug: https://pms.uniontech.com/bug-view-180075.html
Bug: https://pms.uniontech.com/bug-view-180039.html
Change-Id: I0a6ec7c0c29e782ab5f9a7beaad1288a49072376

fix: 修复插入U盘后导致的崩溃问题

---

plugins/tray/snitraywidget.cpp
plugins/tray/snitraywidget.h

fix: 解决SNI应用左键弹出菜单后卡死的问题
将显示菜单的操作移动到主线程中实现
Log:
Influence: 安装新版QQ，左键点击托盘区的QQ，弹出菜单，观察菜单是否可用
Bug: https://pms.uniontech.com/task-view-233111.html

fix: 解决SNI应用左键弹出菜单后卡死的问题

---

frame/util/dockpopupwindow.cpp
frame/util/dockpopupwindow.h
frame/window/quickpluginwindow.cpp
plugins/bluetooth/bluetoothplugin.cpp

移除设备后弹窗不再显示
Log:
Influence: 点击任务栏的蓝牙图标，弹出蓝牙弹窗，然后移除蓝牙，观察蓝牙的弹窗是否存在
Bug: https://pms.uniontech.com/bug-view-181945.html

fix: 修复移除蓝牙后弹框依然显示的问题

---

frame/window/docktraywindow.cpp
frame/window/docktraywindow.h

高效模式最右侧增加显示桌面区域
Log: 增加显示桌面按钮
Influence: 进入高效模式，鼠标进入最右侧，点击，观察是否可以正常显示桌面
Bug: https://pms.uniontech.com/bug-view-180859.html

feat: 高效模式下最右侧增加显示桌面区域

---

frame/util/imageutil.cpp
plugins/multitasking/multitaskingplugin.cpp
plugins/show-desktop/showdesktopplugin.cpp
plugins/trash/trashwidget.cpp

图标加载后，需要将图标缩放成合适的大小
Log: 修复高缩放率下图标显示异常
Influence: 1.25倍缩放率下，选择非默认主题，观察任务栏显示桌面、多任务试图和回收站的图标大小是否正常
Bug: https://pms.uniontech.com/bug-view-182673.html

fix: 修复高缩放率下固定区域图标和回收站图标显示异常的问题

---

frame/window/quickpluginwindow.cpp
plugins/onboard/onboarditem.cpp
plugins/pluginmanager/iconmanager.cpp
plugins/sound/soundwidget.cpp

高缩放率下，需要将图标按照缩放下的图标进行显示
Log: 优化高缩放率下插件图标显示异常
Influence: 高分屏，设置缩放率为最高，观察任务栏插件区域的图标显示是否正常
Bug: https://pms.uniontech.com/bug-view-183543.html

fix: 修复高缩放率下插件图标显示异常的问题

---

frame/window/tray/tray_delegate.cpp
frame/window/tray/tray_delegate.h
frame/window/tray/tray_gridview.h
frame/window/tray/widgets/expandiconwidget.cpp
frame/window/tray/widgets/systempluginitem.cpp
frame/window/tray/widgets/systempluginitem.h
plugins/pluginmanager/dockplugincontroller.cpp

原因：在鼠标点击托盘内右键菜单的时候，会隐藏托盘，导致菜单跟着隐藏，结果是菜单的相关功能不生效
解决方案：在点击托盘区域的时候，判断鼠标位置是否在托盘区域内，包括菜单区域，如果在托盘区域内，则不关闭托盘，等菜单点击完成后再关闭
Log: 修复托盘U盘图标右键不生效的问题
Influence: 插入U盘，打开托盘区，右键菜单，点击，观察功能是否生效
Bug: https://pms.uniontech.com/bug-view-182299.html

fix: 修复展开托盘无法通过菜单移除U盘的问题

---

configs/com.deepin.dde.dock.dconfig.json
frame/window/quickpluginwindow.cpp
plugins/bluetooth/bluetoothmainwidget.cpp
plugins/bluetooth/bluetoothmainwidget.h
plugins/pluginmanager/dockplugincontroller.cpp
plugins/pluginmanager/dockplugincontroller.h
plugins/pluginmanager/iconmanager.cpp

1、修复拖动过程中组合图标尺寸显示异常的问题
2、修复从控制中心设置插件显示隐藏引起的异常问题
3、修复高缩放率下的组合图标显示异常问题
4、修复蓝牙面板在不同的主题下颜色的显示的问题
5、社区版键盘布局默认在任务栏显示
Log: 修复图标显示的问题
Influence: 高缩放率下，观察组合图标显示是否正常
Bug: https://pms.uniontech.com/bug-view-181723.html

fix: 修复图标异常问题

---

plugins/bluetooth/bluetoothitem.cpp
plugins/bluetooth/bluetoothitem.h
plugins/bluetooth/bluetoothplugin.cpp
plugins/bluetooth/componments/bluetoothapplet.cpp
plugins/bluetooth/componments/bluetoothapplet.h
plugins/display/displayplugin.cpp
plugins/display/displaysettingwidget.cpp
plugins/display/displaysettingwidget.h
plugins/sound/sounddeviceswidget.cpp
plugins/sound/sounddeviceswidget.h
plugins/sound/soundplugin.cpp

在子插件点击相应的功能按钮的时候，调用requestSetAppletVisible方法来隐藏面板
Log: 优化快捷面板插件功能
Influence: 进入快捷面板的蓝牙子界面点击设置，进入声音子界面点击设置，进入亮度调整子界面点击设置，在弹出对应的功能后，观察快捷面板是否隐藏
Task: https://pms.uniontech.com/task-view-222353.html

fix: 修复快捷面板插件子面板无法关闭主面板的问题

---

frame/window/tray/widgets/xembedtrayitemwidget.cpp

根因：高效模式和时尚模式分别创建了各自的XEmbedTrayItemWidget对象，时尚模式后创建这个对象，在创建这个对象的构造函数中会把QX11Info::connection与容器的id进行配对组合，导致后创建的对象替换了先创建对象的容器id与QX11Info::connection的映射，在点击先创建对象的时候，无法找到对应的匹配关系，导致无法打开XEmbedTrayItemWidget协议对应的窗口 修改：在构造函数不再创建映射，在当前窗口showEvent事件中再对容器id和QX11Info::connection进行映射，这样在点击窗口图标的时候可以打开正确的窗口
Log: 修复高效模式下无法打开企业微信的问题
Influence: 进入高效模式，打开企业微信和微信等应用，观察是否正常打开窗口
Bug: https://pms.uniontech.com/bug-view-182065.html

fix: 修复高效模式下无法打开企业微信的问题

---

frame/window/tray/widgets/expandiconwidget.cpp
frame/window/tray/widgets/expandiconwidget.h

任务栏托盘窗口实现采用的是自定义绘制,与窗口特效不兼容,改用继承DBlurEffectWidget类的方式实现窗口
Log: 修改托盘窗口绘制方式
Bug: https://github.com/linuxdeepin/developer-center/issues/3615

fix: 关闭窗口特效后,任务栏托盘窗口出现四个黑角

---

configs/com.deepin.dde.dock.dconfig.json
plugins/multitasking/multitaskingplugin.cpp
plugins/show-desktop/showdesktopplugin.cpp
plugins/show-desktop/showdesktopplugin.h

1.通过任务栏右键移除按钮时，移除对应插件
2.显示桌面和多任务视图需要加入到快捷插件显示中
Log: 修复任务栏多任务视图不能正常移除的问题
Bug: https://github.com/linuxdeepin/developer-center/issues/3599
Influence: 任务栏显示桌面合多任务视图插件的显示

fix: 任务栏多任务视图不能正常移除

---

configs/org.deepin.dde.dock.power.json
plugins/power/powerplugin.cpp
plugins/power/powerplugin.h

任务栏电源配置原来管理gsetting配置替换成dconfig配置
Log: 修复控制中心设置的电源选项任务栏未生效的问题
resolve: https://github.com/linuxdeepin/developer-center/issues/3768
Influence: 任务栏电池信息显示

fix: 控制中心设置的电源选项任务栏未生效

---

frame/window/components/datetimedisplayer.cpp

当更改了时间显示格式后，需要更新下menu菜单的显示状态
Log: 修复任务栏时间右键菜单时间格式显示错误的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/3792
Influence: 任务栏时间插件右键菜单

fix: 任务栏时间右键菜单时间格式显示错误

---

frame/window/windowmanager.cpp

dock only set postion calculated by current screen without curren screen x,y offset from top-left.
log: fix launcher appears in the wrong place

fix: fix launcher show at a worng postion when using multi screen

---

CMakeLists.txt

把生成文件扔到build文件夹，这样文件夹里面就没有需要git额外追踪的文件了

chore: move configure to CMAKE_CURRENT_BINARY_DIR

---

frame/main.cpp

According to [Qt's documentation](https://doc.qt.io/qt-5/qt.html#ApplicationAttribute-enum)
> Enables high-DPI scaling in Qt on supported platforms (see also [High DPI Displays](https://doc.qt.io/qt-5/highdpi.html)). Supported platforms are X11, Windows and Android. Enabling makes Qt scale the main (device independent) coordinate system according to display scale factors provided by the operating system. This corresponds to setting the QT_AUTO_SCREEN​_SCALE_FACTOR environment variable to 1. This attribute must be set before [QGuiApplication](https://doc.qt.io/qt-5/qguiapplication.html) is constructed. This value was added in Qt 5.6.
AA_EnableHighDpiScaling need to be set before QGuiApplication constructed.
log:

fix: AA_EnableHighDpiScaling setted after QGuiApplication constructed.

---

plugins/trash/CMakeLists.txt
plugins/trash/trashwidget.cpp

Modify Trash Icon's calculation way, which is flowing on LauncherItem.
Issue: https://github.com/linuxdeepin/developer-center/issues/3588

fix: Trash's icon is too large in small dock

---

frame/item/components/appsnapshot.cpp

get a QImage copy data to prevent XDestroyImage clear image data which make a empty QImage
log:

fix: fix some window preview crash

---

frame/main.cpp

使用DDE作为当前桌面环境的名称
https://github.com/linuxdeepin/developer-center/issues/3829
log:

chore: use DDE for current desktop name

---

frame/window/tray/tray_model.cpp

fix https://github.com/linuxdeepin/developer-center/issues/3575
expandIcon can't be draged but can be selected, selected status generated by keep left-clicking undraggable expandIcon.
So by removing selectable attr, selected status will never generated.
log:

fix: remove tray item selected status

---

plugins/bluetooth/bluetoothmainwidget.cpp
plugins/pluginmanager/standardquickitem.cpp
plugins/power/powerplugin.cpp

修复dde-dock的逻辑,但自定义插件需要各应用自己修复相关逻辑
resolve: https://github.com/linuxdeepin/developer-center/issues/3574
Log: 修复当字体大小设置为20时控制面板字体显示错误

fix: fix quick control panel display text incorrectly when fontSize set to 20

---

frame/window/quickpluginmodel.cpp

resolve: https://github.com/linuxdeepin/developer-center/issues/3915
Log: 修复拖动快捷插件到托盘上时托盘总被重置的问题

fix: tray always reset while dragging quickItem to trayDock

---

frame/item/appitem.cpp
frame/item/appitem.h

任务栏图标的高亮色跟随系统主题高亮色变化
Log: 修复任务栏图标样式显示异常的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/3921
Influence: 任务栏图标显示

fix: 任务栏图标样式显示异常

---

frame/util/dockpopupwindow.cpp
plugins/pluginmanager/dockplugincontroller.cpp

Disk popup does hide after all disks are ejected. Hide popup of a pluin in itemRemoved, and notify the DockPopupWindow to hide too.
Log: fix disk popup does not hide
Issue: 3813

fix: disk popup does not hide

---

frame/window/mainpanelcontrol.cpp
plugins/multitasking/multitaskingplugin.cpp
plugins/pluginmanager/dockplugincontroller.cpp

1. after dragging nothing handle non-app item restore, while it has a right index
2. Fixed_Plugin also uses QWidget to show, so it also need to set visible after readded
3. multitasking use dbus call direct instead of calling a QProcess

fix dock Fixed_plugin disappear after dragging and setting in control center

---

frame/window/tray/widgets/xembedtrayitemwidget.cpp

fix https://github.com/linuxdeepin/developer-center/issues/3635
xcb create window must map to xembedtray widget, otherwise the window will fly out

fix: fix xembed tray flew out

---

frame/item/components/appdragwidget.cpp
frame/item/dockitem.cpp
frame/util/dockpopupwindow.cpp
frame/util/dockpopupwindow.h
frame/window/components/datetimedisplayer.cpp
frame/window/docktraywindow.cpp
frame/window/quickpluginwindow.cpp
frame/window/systempluginwindow.cpp
frame/window/tray/tray_delegate.cpp
frame/window/tray/widgets/snitrayitemwidget.cpp
frame/window/tray/widgets/systempluginitem.cpp
interfaces/constants.h
plugins/sound/sounddeviceswidget.cpp

DockPopupWindow改为使用DBlurEffectWidget来实现新的设计，以及摆脱原来DArrowRectangle出现的侧边任务栏PopupWindow圆角显示不对称的问题．同时，当前遗留有QuickPlugin与DateTimePlayer的HoverTip Padding和其他不太一致的问题．
Log: DockPopupWindow改用DBlurEffectWidget实现

feat: DockPopupWindow改用DBlurEffectWidget实现

---

frame/util/dockpopupwindow.cpp
frame/util/dockpopupwindow.h

Log: fix when there is focus and dockpopupwindow hide
Resolve: https://github.com/linuxdeepin/developer-center/issues/3830

fix: when there is focus on dockpopupwindow, it hide

---

frame/window/components/datetimedisplayer.cpp
frame/window/components/datetimedisplayer.h
frame/window/docktraywindow.cpp

when font size changed, timedate widget need to update width and height, and call DFontSizeManager only when font changed.
in some case dateTimeWidget QWIDGETSIZE_MAX will get a huge size, so use `min(QWIDGETSIZE_MAX, parent->height());` limit max height.
log: fix timedate widget size erorr

fix: fix timedate display widget size error

---

frame/window/tray/widgets/snitrayitemwidget.cpp

when first left click SNI tray menu and app without activate to show, will get a dbus error and recall right menu
this will case menu unable to click, move recall to another thread
log: fix SNI tray menu unable to click

fix: SNI tray menu unable to click

---

plugins/pluginmanager/iconmanager.cpp

由于 dci 图标殷勤不再乘以缩放，这里不需要再次处理了
见： https://github.com/linuxdeepin/qt5integration/pull/149
Change-Id: I88b9959be0ec88fb3e420b60d7badc5aef772f1d

fix: dci icon size incorrect

---

frame/window/mainpanelcontrol.cpp

RequestDock dbus call, only local path passed into without scheme
Resolve: https://github.com/linuxdeepin/developer-center/issues/4101
log: fix unable drag desktop info dock and make it docked

fix: unable drag desktop into dock

---

plugins/multitasking/multitaskingplugin.cpp
plugins/show-desktop/showdesktopplugin.cpp

The removal will actually remove the plugin, which will make the removed plugin inaccessible, making it impossible to set the plug-in to the dock in the dde-control-center.
Therefore, instead of calling the remove method, set the plugin to hide from the dock.
log: make fixed_plugin hide instead of removal when click ondock

fix: click undock menu which make fixed_plugin hide always

---

plugins/overlay-warning/overlay-warning-plugin.cpp
plugins/shutdown/shutdownplugin.cpp

详细描述: plugins/overlay-warning/overlay-warning-plugin.cpp中isOverlayRoot函数打开/proc/cmdline文件的操作可能会失败需要添加判断语句优化，同时为其他打开文件失败分支添加了qWarning报警。

Fix: optimize QFile operation

---

CMakeLists.txt
plugins/plugin-guide/home_monitor/CMakeLists.txt

Log:
Never modify the value of CMAKE_INSTALL_PREFIX after including GNUInstallDirs ，Otherwise incorrect CMAKE_INSTALL_FULL_XXXX values will be computed

fix: must set CMAKE_INSTALL_PREFIX before GNUInstallDirs

---

frame/window/quickpluginwindow.cpp

When screen-recorder finish recording, will notify dock update item, and dock will clean all item and readded back. But m_dragInfo->dockItem still point to old item which has been cleaned.
So dock will coredump, while using this pointer to judge item can drag or not.
Resolve: https://github.com/linuxdeepin/developer-center/issues/4245

fix: after screen-recorder finished, dock will coredump

---

frame/window/mainwindowbase.cpp
frame/window/mainwindowbase.h
frame/window/traymainwindow.cpp
frame/window/traymainwindow.h

make m_platformWindowHandle protected so subclass can connect to windowRadiusChanged signal, which make traymainwindow radius change follow mainwindow
log: make trymainwindows radius changed follow mainwindow

fix: set radius for tray inner window

---

plugins/pluginmanager/iconmanager.cpp

DCI iconengine will automatically switch to correct icon when theme type changes. Application should not do anything after getting the pixmap.
Log: fix wrong use of dci icon

fix: wrong use of dci icon

---

frame/util/dockpopupwindow.cpp

Log: only not hide it when focus widget is QLineEdit

fix: popupwindow need click destkop twice to hide

---

frame/controller/toolapphelper.cpp

relayout after updateToolArea otherwise plugin item size will set to 0
log:  only relayout after update visiable

fix: trash do not display when dock hide and trash readded into dock

---

frame/util/dockpopupwindow.cpp

content should not more width than screen otherwise popupwindows must be out of bounds screen
log: as title

fix: popupwindow misjudgment

---

frame/window/components/datetimedisplayer.cpp
frame/window/components/datetimedisplayer.h

when the sum of the pixel dimensions of the time font and the date font is the same as the height, leave some space so the text doesn't look too crowded.
log: adjust timedate size

fix: timedate size issue

---

frame/window/components/datetimedisplayer.cpp

update dateFont size when DateTimeDisplayer size changed.

fix: dock position changed from left to bottom no date display

---

frame/util/dockpopupwindow.cpp

It causes that child widgets doesn't have focus even though
calling setFocus.
It was introduced by ec5c447264087420d8ec80a18e7f2bcc4f683a74.
because that DArrowRectangle has activateWindow when show.
Issue: https://pms.uniontech.com/bug-view-172773.html

fix: DockPopupWindow losing active status

---

frame/window/tray/tray_delegate.cpp
frame/window/tray/tray_delegate.h
frame/window/tray/widgets/indicatortrayitem.cpp
frame/window/tray/widgets/indicatortrayitem.h

1. indicator icon size shou be fixed same as other tray icon, should not change follow system font size.
2. add text change info from sourceIndicatorWidget to display indicatorWidget
3. adjust tray icon to 20 pixel.
Resolve: https://github.com/linuxdeepin/developer-center/issues/3834
Resolve: https://github.com/linuxdeepin/developer-center/issues/4321

fix: make keyboard layout plugin size fixed and adjust tray icon size

---

widgets/tipswidget.cpp

note: rounded corner level is 'large'
Resolve: https://github.com/linuxdeepin/developer-center/issues/4640
Log: 修复当dock插件的提示文本是多行时, 文本显示不全的问题

fix: imcomplete display when dock plugin's tips text is multi-line

---

plugins/sound/sounddeviceswidget.cpp

取消声音面板设备悬浮提示
Log: 修复任务栏声音面板中出现异常的悬浮提示的问题
Influence: 任务栏声音面板正常显示
Resolve: https://github.com/linuxdeepin/developer-center/issues/4368

fix: 任务栏声音面板中出现异常的悬浮提示

---

plugins/sound/sounddeviceswidget.cpp

We can edit the name of sound device in the dock, it should not be happened. 
Just set the item uneditable.
Log:
close linuxdeepin/developer-center#4752

fix: the name of sound device shouldn't be edited

---

frame/taskmanager/appinfo.cpp
frame/taskmanager/desktopinfo.cpp
frame/taskmanager/windowidentify.cpp

window_patterns.json used for app in store, and it return cn.google.chrome, whcih is not installed. So, it means that identifyWindowByRule may return a invalid appinfo. Return nullptr if it's invalid appinfo.
implement DesktopInfo::isInstalled
log: fix identifyWindowByRule return a invalid appinfo

fix: official chrome unable to be identified

---

frame/controller/dockitemmanager.cpp

Current entryRemove and entryAdded connection is not thread-safe. Although entryRemove before entryAdded sended, entryRemove slot do later than entryAdded slot, which make added entry (later signal) removed by previous entryRemove signal.
log: make entryRemove and entryAdded connecttion thread-safe.

fix: some app do not display

---

frame/item/components/appsnapshot.cpp

drawPixmap will scale pixmap to fit imageRect, but not KeepAspectRatio
log: as title

fix: applicationpreview scale not keep aspectratio

---

frame/window/tray/widgets/expandiconwidget.cpp

expandiconwidget get focus when click tray, so it will alway activate application because lost focus.
log: set WindowDoesNotAcceptFocus for TrayGridWidget

fix: click always activate application in TrayGridWidget

---

frame/window/tray/widgets/snitrayitemwidget.cpp

initMenu failed to create menu which make m_menu is still nullptr
log: as title

fix: coredump when open jetbrains-toolbox

---

frame/window/docktraywindow.cpp
frame/window/tray/tray_delegate.cpp
frame/window/tray/tray_delegate.h
frame/window/tray/tray_gridview.cpp
frame/window/tray/tray_gridview.h
frame/window/tray/widgets/expandiconwidget.cpp
frame/window/traymanagerwindow.cpp

The tray in fashion mode is not the same object as the tray in efficient mode, and only one xembedtray is vaild, so there will be a contention between the two. The latter xembedtray who call reparent() will be the vaild one. So drag from expandiconwidget, the xembed tray click in the efficient mode get no response while the tray click get response when switching from the fashion mode.
log: make tray(both fashion and efficient mode) to be one object

fix: xebmbedtary click get no response in Efficient mode

---

frame/item/appitem.cpp
frame/item/components/previewcontainer.cpp

it connect to a empty signal
Log:

fix: click preview container not active window

---

frame/window/docktraywindow.cpp

fix: tray get a wrong postion after displaymode changed

---

frame/window/tray/tray_gridview.cpp
frame/window/traymanagerwindow.cpp

Fashion mode and Efficent mode has same one tray, when tray is empty and update orientation will cause endless reseize event which case dock stack boom
log: move TrayGridView Orientation update into TrayGridView

fix: coredump empty tray when switch postion

---

frame/util/dockpopupwindow.cpp

We hide the popupwindow when receiving QEvent::WindowDeactivate.
Issue: https://github.com/linuxdeepin/developer-center/issues/5405

fix: Can't hide when DockPopupWindow deactivate

---

plugins/display/brightnessadjwidget.cpp
plugins/display/brightnessadjwidget.h
plugins/display/brightnessmodel.cpp
plugins/display/brightnessmodel.h
plugins/display/displayplugin.cpp
plugins/display/displaysettingwidget.cpp
plugins/display/displaysettingwidget.h

changedProps.vale get a empty monitors list, and BrightnessAdjWidget not update  monitor SliderContainer count
log: fix displayplugin disappear

fix: displayplugin disappear when monitor count changed

---

plugins/display/brightnessmodel.cpp

double 0.29 * 100 then cast to init, it is 28
Log:

 fix: brightness silder cannot scroll when value is 28 or 56

---

frame/util/docksettings.cpp

Fallback to default value if dconfig::value failed if not specify a fallback, default is QVariant()

chore: get dconfig value with fallback value

---

plugins/bluetooth/componments/bluetoothadapteritem.cpp
plugins/power/powerstatuswidget.cpp

Log:
Icon 主题已经修复了，所以不需要在亮色强制用暗色了，
电源图标也用默认的即可

feat: use system battery icon first

---

frame/dbus/dbusdockadaptors.cpp

use svg format instead of png to support scaling on DPR>1.0
Issue: https://github.com/linuxdeepin/developer-center/issues/5682

fix: dcc dock plugin icon pixelated

---

frame/dbus/dbusdockadaptors.cpp
plugins/multitasking/multitaskingplugin.cpp
plugins/show-desktop/CMakeLists.txt
plugins/show-desktop/showdesktopplugin.cpp
plugins/shutdown/CMakeLists.txt
plugins/shutdown/shutdownplugin.cpp
plugins/sound/sounddeviceswidget.cpp
plugins/trash/trashplugin.cpp

- 部分图片路径写错
- 资源图片直接加到qicon中，qicon.availableSizes[0]={0, 0}
- 部分插件没有适配主题颜色
Issue: https://github.com/linuxdeepin/developer-center/issues/5682

 fix: dcc dock plugin icon pixelated again

---

plugins/bluetooth/componments/bluetoothadapteritem.cpp

change loading animation when bluetooth switch
Issue: https://github.com/linuxdeepin/developer-center/issues/6033

fix: turn on bluetooth loading animation not start

---

plugins/bluetooth/componments/bluetoothadapteritem.cpp

关闭蓝牙后还会收到上一个操作的设备扫描的新增信号
解决方案是关闭后不再响应这个信号
Issue: https://github.com/linuxdeepin/developer-center/issues/6033

fix: item hight error when turn off bluetooth

---

plugins/media/mediaplayermodel.cpp
plugins/media/mediaplayermodel.h
plugins/media/mediawidget.cpp

关闭一个播放器后无法再次控制剩余的播放器
记录所有的播放器控制接口，退出一个后回退到上一个播放器控制
如果没有提供默认专辑和歌手信息图标等返回一个默认的图标和文字（未翻译）如firefox 播放酷狗音乐只有一个title，其他歌曲信息都没的
Issue: https://github.com/linuxdeepin/developer-center/issues/5719

fix: 任务栏媒体播放插件异常

---

frame/taskmanager/taskmanager.cpp
frame/taskmanager/taskmanager.h
frame/util/dockpopupwindow.cpp

MainWindow should not hide when popup opens and the focus is still on dock even if HideMode is AlwaysHide. Let popup block hiding of mainwindow.
Log: fix mainwindow hide when popup opens
Issue: https://github.com/linuxdeepin/developer-center/issues/4970

fix: mainwindow hide when popup opens

---

frame/window/quickpluginwindow.cpp
frame/window/quickpluginwindow.h

Item context menu is not updated when plugin item request update.
Log: fix item context menu not updated

fix: item context menu not updated

---

frame/window/components/datetimedisplayer.cpp

call com.deepin.Calendar dbus instead org.deepin.dde.Widgets1
log: as title

feat: open deepin-calendar instead of dde-widgets when click timedate

---

plugins/notification/notification.cpp
plugins/notification/notification.h

Cannot create a child in another thread. Do not use object tree, use QScopedPointer to manage life scope.
Log: fix cross-thread parenting failure

fix: cross-thread parenting failure

---

frame/window/quickpluginwindow.cpp

Parsing item context menu may fail, always check context menu in mousePressEvent.
Log: fix item menu may be empty due to error

fix: item menu may be empty due to error

---

CMakeLists.txt
debian/changelog

bump version 6.0.27
log: as title

chore: release 6.0.27

---

plugins/pluginmanager/standardquickitem.cpp

battery should use fallback icon when in dark theme, because it will always find the light theme.
update quickItem when theme changed
Log:

fix: quickpanel icon not follow theme

---

plugins/onboard/onboardplugin.cpp

tray to call show when onboard not launched
log: s title

fix: onboard not to show on first click

---

frame/util/multiscreenworker.cpp

When dock is hidden, position change through DBus will not change frontend rect, thus not update wakeup area. This is because position in WindowManager is not changed. Emit positionChanged signal in MultiScreenWorker.
Log: fix dock wakeup area not changed
Issue: https://github.com/linuxdeepin/developer-center/issues/5831

fix: dock wakeup area not changed

---

frame/taskmanager/dbushandler.cpp
frame/taskmanager/dbushandler.h
frame/taskmanager/taskmanager.cpp

undock items that removed
Issus: https://github.com/linuxdeepin/developer-center/issues/4631

fix: the item that removed is exist yet

---

frame/util/dockpopupwindow.cpp

Use setFixedSize instead of resize so that dock popup window is not
resizable.
Log: disable resize of dock popup window
Issue: https://github.com/linuxdeepin/developer-center/issues/6264

fix: disable resize of dock popup window

---

CMakeLists.txt
debian/changelog

chore: release 6.0.28

---

frame/util/multiscreenworker.cpp
frame/window/mainwindowbase.cpp

no one update hideState properties in taskmanager and not update dockSize when dock is in hide state by resetDragWindow call
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7040

fix: dock get max size when positionChanged and KeepHide mode

---

frame/window/quickpluginwindow.cpp
plugins/pluginmanager/quicksettingitem.cpp

fix: tmp blocked uosai plugin in quickpanel

---

CMakeLists.txt
debian/changelog

bump version 6.0.32
log: as title

chore: bump version 6.0.32

---

frame/util/multiscreenworker.cpp

update dock item position
log: as title
issue: https://github.com/linuxdeepin/developer-center/issues/7097

fix: dock item indicator not update

---

CMakeLists.txt
debian/changelog

chore: release version 6.0.34

---

CMakeLists.txt
debian/changelog
frame/util/multiscreenworker.cpp
frame/util/multiscreenworker.h
frame/window/mainpanelcontrol.cpp
frame/window/mainwindowbase.cpp
frame/window/traymanagerwindow.cpp
frame/window/windowmanager.cpp
plugins/pluginmanager/quicksettingitem.cpp
plugins/pluginmanager/standardquickitem.cpp
widgets/slidercontainer.cpp

chore: adjust dock ui

---

plugins/bluetooth/bluetoothmainwidget.cpp
plugins/bluetooth/bluetoothmainwidget.h
plugins/bluetooth/resources/bluetooth.qrc

快捷面板中蓝牙图标和网络插件保持一致
- 大小一致 24x24
- 选中时高亮色填充
- 圆图标
Issue: https://github.com/linuxdeepin/developer-center/issues/7207

fix: bluetooth quick-trays item icon tweak

---

frame/window/tray/tray_monitor.cpp
frame/window/tray/widgets/basetraywidget.cpp
frame/window/tray/widgets/basetraywidget.h
frame/window/tray/widgets/snitrayitemwidget.cpp
frame/window/tray/widgets/xembedtrayitemwidget.cpp
frame/window/tray/widgets/xembedtrayitemwidget.h

some gtk apps use libayatana-appindicator create tray will create xembed and sni duplicate tray not show sni tray which path contains /org/ayatana/NotificationItem/ created by ayatana-appindicator
log: not show ayatana-appindicator sni tray on xorg

fix: duplicate tray for some app

---

frame/window/tray/widgets/expandiconwidget.cpp

remove ToolTip windowflag
Bug: https://pms.uniontech.com/bug-view-239173.html
Issue: https://github.com/linuxdeepin/developer-center/issues/7612

fix: wine app menu obscured by popup widget
